using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Chest : MonoBehaviour,IInteractable 
{
    private SpriteRenderer spriteRenderer;
    public Sprite openSprite;
    public Sprite closeSprite;
    public bool isDone;
    private PickupSpawner pickupSpawner;   //딜쭝돛야신굶돨多痰

    private void Awake()
    {
        spriteRenderer =GetComponent<SpriteRenderer>();
        pickupSpawner = GetComponent<PickupSpawner>();
    }

    private void OnEnable()
    {
        spriteRenderer .sprite =isDone?openSprite : closeSprite;
    }
    public void TriggerAction()
    {
        Debug.Log("open");
        if (!isDone)
        {
            OpenChest();
        }
    }

    public void OpenChest()
    {
        spriteRenderer.sprite = openSprite;
        isDone = true;
        pickupSpawner.DropItems();
        this.gameObject.tag = "Untagged";
    }
}
