using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

public class SavePoint : MonoBehaviour,IInteractable   //쌈왯
{
    [Header("밤꺄")]
    public VoidEventSO saveDataEvent;

    [Header("긴좆꽝鑒")]
    public  SpriteRenderer spriteRenderer;

    public bool isDone;
    public GameObject SaveSprite;
    public Sprite lightSprite;

    private void OnEnable()
    {
        SaveSprite.SetActive(isDone);
    }

    public void TriggerAction()
    {
        if (!isDone)
        {
            isDone = true;
            //spriteRenderer.sprite = lightSprite;
            SaveSprite.SetActive(true);
            saveDataEvent.RaiseEvent();

            this.gameObject.tag = "Untagged";
        }
    }
}